### ISSUE TITLE
Aggregation not working

### ISSUE THREAD

**Issue by dhatawesomedude** [jsreport/jsreport-contrib-mongodb#1]
Is aggregation unsupported?

Whenever I try to use aggregation, I get this strange error. Find works okay, but aggregation always throws this erorr.
`Error occured - Error during rendering report: Cannot read property 'toArray' of undefined
Stack - Error: Cannot read property 'toArray' of undefined
    at ChildProcess.<anonymous> (/root/node_modules/jsreport/node_modules/toner/node_modules/script-manager/lib/manager-processes.js:38:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
From previous event:
    at /root/node_modules/jsreport/extension/scripts/lib/scripts.js:124:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
From previous event:
    at Scripts.handleBeforeRender (/root/node_modules/jsreport/extension/scripts/lib/scripts.js:99:25)
    at /root/node_modules/jsreport/lib/util/listenerCollection.js:172:41
    at /root/node_modules/jsreport/lib/util/listenerCollection.js:151:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
`

**Comment by dhatawesomedude** [comment]
Here's my aggregate query.

`var collection = db.collection('jobs_models').aggregate([stage1, stage2, stage3, stage4, stage5]).toArray(function(err, jobs) {
             if (!err) {                        
                    request.data = { 
                        "debtor_jobs": jobs
                    };
                    done();
                }         
        });
`

**Comment by pofider** [comment]
From the mongodb docs...

``` js
collection.aggregate([
          { $project : {
            author : 1,
            tags : 1
          }},
          { $unwind : "$tags" },
          { $group : {
            _id : {tags : "$tags"},
            authors : { $addToSet : "$author" }
          }}
        ], function(err, result) {
          console.dir(result);
          db.close();
      });
```

Seems you should put the callback as the last argument of aggregate. 

Note this is not the place for asking mongodb questions. This is just requiring mongodb module into jsreport, there is nothing more. Everything that works in mongodb driver will work here.

**Comment by pofider** [comment]
Maybe the problem was that this package uses quite old mongodb driver
https://github.com/jsreport/jsreport-contrib-mongodb/blob/master/package.json#L24
I'm sorry if this was the problem.

**Comment by dhatawesomedude** [comment]
Thanks. Yes, I did figure that out after I had posted here. I think It's because of the older driver.
